import { z } from 'zod';

/**
 * Raw scraped event data before normalization
 */
export interface RawEvent {
  title: string;
  rawHtml?: string;
  rawText?: string;
  url?: string;
  imageUrl?: string;
  rawDate?: string;
  rawTime?: string;
  rawEndTime?: string; // For events with time ranges
  rawVenue?: string;
  rawPrice?: string;
  rawDescription?: string;
  metadata?: Record<string, any>;
}

/**
 * Normalized event data ready for database insertion
 */
export interface NormalizedEvent {
  title: string;
  normalizedTitle: string;
  description?: string;
  startDateTime: Date;
  endDateTime?: Date;
  timezone: string;
  venueId?: string; // Set by venue matcher
  venueName: string;
  category: string[];
  tags: string[];
  images: string[];
  ticketUrl?: string;
  priceMin?: number;
  priceMax?: number;
  isFree: boolean;
  ageRestriction?: string;
  embedding?: number[]; // OpenAI embedding
  sourceUrl: string;
  sourceName: string;
  rawData: Record<string, any>;
}

/**
 * Scraper statistics for monitoring
 */
export interface ScraperStats {
  eventsFound: number;
  eventsNew: number;
  eventsUpdated: number;
  eventsDuplicate: number;
  eventsFlagged: number;
  errors: number;
  duration: number;
}

/**
 * Base interface for all scraper agents
 */
export interface ScraperAgent {
  name: string;
  sourceUrl: string;
  schedule: string; // Cron expression

  /**
   * Scrape raw event data from source
   */
  scrape(): Promise<RawEvent[]>;

  /**
   * Normalize raw event using Claude AI
   */
  normalize(raw: RawEvent): Promise<NormalizedEvent>;

  /**
   * Check for duplicates using pgvector similarity
   * Returns existing event ID if duplicate, or creates new event
   */
  deduplicate(event: NormalizedEvent): Promise<string>;

  /**
   * Main execution: scrape → normalize → deduplicate
   */
  run(): Promise<ScraperStats>;
}

/**
 * Scraper run status
 */
export enum ScraperStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL', // Some events succeeded, some failed
}

/**
 * Scraper run record for database
 */
export interface ScraperRun {
  id?: string;
  sourceName: string;
  sourceUrl?: string;
  status: ScraperStatus;
  eventsFound: number;
  eventsNew: number;
  eventsUpdated: number;
  errorMessage?: string;
  metadata?: Record<string, any>;
  startedAt: Date;
  completedAt?: Date;
}

/**
 * Duplicate detection result
 */
export interface DuplicateResult {
  isDuplicate: boolean;
  eventId?: string; // Existing event ID if duplicate
  similarityScore?: number;
  action: 'create' | 'update' | 'merge' | 'flag'; // What action was taken
}

/**
 * Venue matching result
 */
export interface VenueMatch {
  venueId: string;
  venueName: string;
  normalizedName: string;
  confidence: number;
  isNew: boolean;
}

/**
 * Claude normalization prompt response schema
 */
export const ClaudeEventSchema = z.object({
  title: z.string(),
  description: z.string().optional(),
  startDate: z.string(), // ISO format
  endDate: z.string().optional(), // ISO format
  venueName: z.string(),
  category: z.array(z.string()),
  tags: z.array(z.string()),
  priceMin: z.number().optional(),
  priceMax: z.number().optional(),
  isFree: z.boolean(),
  ageRestriction: z.string().optional(),
});

export type ClaudeEventResponse = z.infer<typeof ClaudeEventSchema>;

/**
 * Scraper configuration
 */
export interface ScraperConfig {
  name: string;
  sourceUrl: string;
  schedule: string;
  enabled: boolean;
  timeout: number; // milliseconds
  retries: number;
  rateLimitMs: number; // milliseconds between requests
}

/**
 * Orchestrator configuration
 */
export interface OrchestratorConfig {
  scrapers: ScraperConfig[];
  redis: {
    host: string;
    port: number;
    password?: string;
  };
  concurrency: number; // Max concurrent scrapers
  alertThreshold: number; // Consecutive failures before alert
}

/**
 * HTTP fetch options for scrapers
 */
export interface FetchOptions {
  timeout?: number;
  retries?: number;
  headers?: Record<string, string>;
  method?: 'GET' | 'POST';
  body?: any;
}

/**
 * Embedding generation options
 */
export interface EmbeddingOptions {
  model?: string;
  dimensions?: number;
  batchSize?: number;
}

/**
 * Similarity search options
 */
export interface SimilaritySearchOptions {
  threshold: number; // Minimum similarity score (0-1)
  limit: number; // Max results to return
  timeWindow?: number; // Hours to search within (temporal proximity)
  venueId?: string; // Restrict to specific venue
}

/**
 * Page analysis result stored on VenueScraperConfig.
 * Generated by the analyze action, consumed by the refresh action.
 */
export interface PageAnalysis {
  version: 1;
  pageDescription: string;
  extractionPrompt: string;
  pageType: 'static' | 'js-rendered' | 'spa' | 'infinite-scroll';
  waitStrategy: 'networkidle' | 'selector' | 'timeout';
  waitValue?: string;
  requiresScrolling: boolean;
  sampleEventCount: number;
  sampleTitles: string[];
  cleanTextSize: number;
}

// All types are exported as named exports above
